name: SoulPrecls
version: '${project.version}'
main: org.example1.soulprecls.SoulPrecls
api-version: '1.16'
commands:
  pvesea:
    permission: soulitems
    description: выдает пве штууку
    usage: /pvesea
  enderframe:
    permission: soulitems
    description: выдает рамку портала в энд
    usage: /enderframe
