name: SoulPrecls
version: '${project.version}'
main: org.example1.soulprecls.SoulPrecls
api-version: '1.16'
commands:
  enderframe:
    permission: nightItems
    description: выдает рамку портала в энд
    usage: /enderframe
